"""added double rachet algo

Revision ID: a7648070e6a9
Revises: af27c3ab1bab
Create Date: 2026-09-28 13:56:47.283538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7648070e6a9'
down_revision: Union[str, Sequence[str], None] = 'af27c3ab1bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_time_prekeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_one_time_prekeys_user_id'), 'one_time_prekeys', ['user_id'], unique=False)
    op.add_column('user_e2ee', sa.Column('signed_prekey', sa.Text(), nullable=True))
    op.add_column('user_e2ee', sa.Column('signed_prekey_id', sa.Integer(), nullable=True))
    op.add_column('user_e2ee', sa.Column('spk_signature', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_e2ee', 'spk_signature')
    op.drop_column('user_e2ee', 'signed_prekey_id')
    op.drop_column('user_e2ee', 'signed_prekey')
    op.drop_index(op.f('ix_one_time_prekeys_user_id'), table_name='one_time_prekeys')
    op.drop_table('one_time_prekeys')
    # ### end Alembic commands ###
