"""E2EE provided using AES-GCM

Revision ID: af27c3ab1bab
Revises: 2a7370ca9c82
Create Date: 2026-09-25 17:28:11.285458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af27c3ab1bab'
down_revision: Union[str, Sequence[str], None] = '2a7370ca9c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
